  0%|          | 0/352 [00:00<?, ?it/s]/home/home01/sclaam/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:490: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))





















































Train Epoch 0 Iters 301 Train loss 1.591865: 100%|██████████| 352/352 [01:49<00:00,  3.23it/s]
Traceback (most recent call last):
  File "multiprocesing_test.py", line 977, in <module>
    manual_SAM_optimization(cfg)
  File "multiprocesing_test.py", line 818, in manual_SAM_optimization
    wandb.log("train_FLOPS", training_FLOPS, step=global_step)
  File "/home/home01/sclaam/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/home01/sclaam/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
TypeError: log() got multiple values for argument 'step'